spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/storage
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:db/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: grigoreguzun01@gmail.com
    password: ctho ukfb vxtm jbsy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB

storage:
  minio:
    url: http://localhost:9000
    root-user: admin
    root-password: Secure123$
    main-bucket: storage
  mail:
    from: grigoreguzun01@gmail.com
    base-url: http://localhost:8080
  schedule:
    cron: "0 0/20 * * * ?"