spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/storage
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:db/master.xml

storage:
  minio:
    url: http://localhost:9000
    root-user: admin
    root-password: Secure123$
